"""Final legends for the frozen-result figure redesign."""
LEGENDS = {
'Figure_1': (
'Study framework, spatial architecture and NC3 reference mapping',
'a, Arrows link resources to analyses; the dashed Ogden link supplies the state reference. AI-generated schematic icons: OpenAI imagegen. Patient counts refer to analysis-specific subsets. Ogden’s 14 denotes component discovery. Atlas is an acquisition container; E-MTAB-12022/12043 share four patients; ten same-section patients are among eleven with paired regions. NC3, source population; REC, reference state; HRC, primary regenerative readout; REC50, auxiliary projection. b, P02 (dHGP) and P18 (rHGP) ISS fields share a coordinate scale; the overview locates the P18 crop. Analyses use complete fields. c,d, NC3 fraction and the fraction with ≥1 liver epithelial neighbour (ten-neighbour graph), both among neoplastic cells. Points: 7 dHGP, 8 rHGP patients; bars: means, with equal within-patient ROI weights. e, Observed-minus-conditional-null adjacency and patient-bootstrap 95% intervals. Homotypic adjacency requires another NC3 neighbour; dual adjacency requires both NC3 and damaged-hepatocyte (DHC) neighbours around an NC3 cell. The null preserves local abundance, anatomical strata and coordinates. pp, percentage points. f, ISS × Ogden centroid Pearson correlations across 94 genes. NC3–REC (r = 0.387) is outlined. Colono., Colonocyte; Interm., Intermediate; Stem-N., Stem NOTUM. Robustness: Supplementary Fig. 1 and Table 2.'),
'Figure_2': (
'Component differences in discovery and independent malignant-cell studies',
'a,b, Within-patient claudin–HRC and polarity–HRC partial Spearman correlations in fourteen Ogden and 28 external patients, on a shared axis. Lines connect each patient; paired endpoints share a fixed horizontal display offset. Harmonized fixed-background scores use the common technical, RSC, iCMS and E2F covariates, with specimen indicators where applicable. c, Five original-study means and the random-effects summary of patient Fisher-z differences. Study intervals are patient-bootstrap percentiles; the pooled interval uses Hartung–Knapp inference. Numbers in parentheses are patients. d, Discovery measurement checks retain the original scoring and state-adjusted model: full 20:8 membership, 500 size-matched 8:8 subsets, and seven expression/detection-matched pairs. Circles subtract fixed backgrounds; squares change component targets to means while retaining HRC and covariates. Intervals resample patients; subset effects are first averaged within patient. The common-model difference in a is 0.112, harmonized state-adjusted difference 0.093, and original discovery difference in d 0.096. Study omissions and alternative external scoring are in Supplementary Fig. 3; matching details are in Supplementary Fig. 2 and Supplementary Table 3.'),
'Figure_3': (
'Complete junction-member associations, study heterogeneity and cellular sources',
'All thirty predefined members share a fixed row order. a, Equal-patient mean detection fractions in epithelial, hepatocyte, endothelial and stromal compartments; the aligned n row gives contributing patient counts. b, Harmonized state-adjusted Ogden gene–HRC correlations and nominal patient-bootstrap 95% intervals; n denotes evaluable patients. Single-patient estimates are shown without confidence intervals. Filled points in b do not encode significance. c, External random-effects correlations with Hartung–Knapp 95% intervals; k denotes contributing studies. Filled/open markers in c indicate thirty-member BH q < 0.05/≥0.05. d, Individual original-study estimates, calculated by back-transforming the saved study Fisher-z means. All 150 study–member combinations are retained: 125 estimable and 25 unavailable. Dots indicate insufficient measurable variation; NA marks unavailable summary estimates. Valid zero and unavailable estimates remain distinct. Detection and correlation use separate colour scales, and the full study-effect range is shown. Bold labels identify discussed members; colour strips distinguish claudins, polarity genes and F11R. Complete estimates, coverage and heterogeneity are in Supplementary Fig. 3 and Supplementary Table 7.'),
'Figure_4': (
'HGP tissue expression and spatial localization',
'a, H&E images from Fleischer et al. [4] (E-MTAB-12043) and computed region overlays for PT55 (dHGP) and PT54 (rHGP), using source registration metadata. Scale bars, 500 μm. Near/deep masks derive from proximity to liver-like expression; all six patients appear in Supplementary Fig. 4. b, Adjusted tumour-side component–HRC correlations in six spatial patients; lines connect components within patient. Blue circles indicate dHGP and orange squares rHGP throughout the patient plots. c, Mean TMM log2 CPM of thirteen count-eligible claudins, from 21 assayed members, in near regions. Points are patients; horizontal lines indicate HGP means. The exact two-sided patient-allocation P is 0.10. d, Independent bulk full-programme HRC (97 genes) and whole-junction (28 genes) scores in nine dHGP and six rHGP tumours. These are gene-z projections, not claudin-specific scores. e, rHGP-minus-dHGP differences in patient near-minus-deep expression, with nominal patient-bootstrap 95% intervals. These mean-log2CPM localization contrasts use full measured memberships and library-normalized, scaled-prior values, distinct from c. Normalization, membership and patient localization sensitivities are in Supplementary Fig. 5 and Supplementary Table 4.'),
'Figure_5': (
'Regional transcription before and after source-associated expression adjustment',
'a, Mean gene-standardized TMM logCPM for 88 count-eligible HRC genes in eleven paired micro-/macrotumour regions. Lines connect patients; inference uses paired count models. b, Patient macro-minus-micro differences in three expression proxies; diamonds show means. Proxy markers exclude all HRC and junction targets. c, All 88 paired HRC gene coefficients before and after adding the proxies to patient + region models. Axes share limits and scale; the dashed diagonal indicates equality. The medians (0.559 and 0.137) are descriptive; displayed directional q values come from the original patient-based programme tests. No regression or test across genes is added. d, Six representative junction members under TMM. Grey open circles denote baseline coefficients; dark squares denote source-adjusted coefficients. Bars retain complete approximate QL-Wald 95% intervals; P values derive from QL tests. Full membership, normalization and same-section results are in Supplementary Fig. 6 and Supplementary Table 8. Proxies represent expression rather than cell fractions.'),
'Supplementary_Figure_1': (
'NC3 composition, adjacency and mapping robustness',
'a, Complete neoplastic-state composition for fifteen pure-HGP patients, with equal ROI weighting. The first seven patients are dHGP and the remaining eight rHGP; patients are ordered by NC3 abundance within HGP. b, Four-state rHGP-minus-dHGP liver-adjacency differences and patient-bootstrap 95% intervals. c, NC3 similarity to REC minus its next-closest reference after patient omission. All seventeen ISS and ten evaluable Ogden omissions retain REC as the closest reference; five further Ogden omissions changed reference coverage and remain in the source table. d, Conditional NC3 homotypic and NC3/damaged-hepatocyte adjacency at five, ten and twenty neighbours. Line styles identify scale; blue circles and orange squares identify dHGP and rHGP. Effects and intervals are saved patient-bootstrap results. Zero lines distinguish excess adjacency from the conditional expectation. pp, percentage points. Full mapping metrics, omission records and neighbourhood results are in Supplementary Table 2.'),
'Supplementary_Figure_2': (
'Epithelial states and discovery measurement sensitivity',
'a, Fixed GSEA normalized enrichment scores for REC versus Hypoxia, UPR and iREC, based on nine, six and five paired patients. Dots mark within-run FDR < 0.05. b, Within-REC HRC–junction correlations after removing shared conditioning genes, under technical-only or additional RSC/iCMS adjustment. Open grey points are individual patients; dark points and bars are Fisher-z summaries back-transformed to correlations and patient-bootstrap 95% intervals. c, Six paired REC-minus-other-state Fisher-z differences and 95% bootstrap intervals; labels give paired patient counts. d, Distributions over 500 eight-claudin subsets, under fixed-background and component-target-mean scoring. These describe membership variation, not patient uncertainty. e, Expression/detection matching features: teal circles denote claudins, purple squares polarity genes; lines connect seven selected pairs and open symbols identify unmatched genes. f, Original state-conditioned claudin-minus-polarity differences in fourteen epithelial and nine REC patients, with bootstrap intervals. All-raw scoring changes HRC and covariate scores as well as components; Fig. 2d changes only component targets. Definitions and separate multiplicity families are in Supplementary Table 3.'),
'Supplementary_Figure_3': (
'Independent validation and member-level heterogeneity',
'a, All 28 patient component differences, grouped by the five original studies. Patient labels are study-local identifiers; qualified identities remain in the source data. b, All five study-omission random-effects estimates with Hartung–Knapp 95% intervals. c, Pooled component differences under harmonized fixed-background and all-target-mean scoring, with Hartung–Knapp intervals. b and c share an axis range. d, I² for all thirty members in the fixed row order of Fig. 3; a separate aligned row gives contributing study counts k. Grey cells indicate I² unavailable with fewer than two eligible studies, distinct from valid zero heterogeneity. Estimates are retained regardless of direction or member-level correction. Complete patient, study, scoring and omission results are in Supplementary Table 7.'),
'Supplementary_Figure_4': (
'Expression-defined regions in all six HGP-labelled spatial patients',
'a–c, Desmoplastic PT55, PT61 and PT68; d–f, replacement PT36, PT44 and PT54. Every retained spot is shown with its original coordinate orientation and aspect ratio. The upper/lower tertiles of the epithelial-minus-hepatocyte expression contrast define tumour-side/liver-like masks. Near tumour-side spots lie one to five hexagonal-grid hops from liver-like spots; connected deep spots lie at least six hops away. Other retained spots include the intermediate tertile and tumour-side spots without a finite connection to the liver-like mask. Two-line labels give total, near and deep spot counts. Complete counts, including liver-like and other spots, are in Supplementary Table 4 and source data; coordinates and masks are frozen. These masks represent expression-defined proximity rather than independently annotated pathological tumour boundaries. All six sections enter inference. Coordinate tables and three/seven-hop sensitivity results accompany Supplementary Tables 2 and 4. Spatial coordinates and source data originate from Fleischer et al. [4], E-MTAB-12043; expression-defined masks were computed for this study.'),
'Supplementary_Figure_5': (
'HGP expression, coverage and normalization sensitivity',
'a, All thirty junction members across bulk, whole tumour-side and near-region rHGP-minus-dHGP TMM contrasts. Rows match Fig. 3 and the full range is shown. Grey entries distinguish source absence (×) and abundance ineligibility (/), separately from valid zero. b, Near-region claudin score differences and patient-bootstrap 95% intervals for all 21 assayed or thirteen eligible members under TMM or library normalization. c, Bulk full/disjoint HRC and whole-junction scores and separate epithelial- or liver-adjusted coefficients, with nominal bootstrap intervals. d, Each of six patients’ near-minus-deep expression for claudin, polarity and HRC, using the full-membership, library-normalized localization scores of Fig. 4e. e, Top-ten transcript fractions versus log2 TMM factors in fifteen bulk and six spatial patients per context. Blue circles/orange squares indicate dHGP/rHGP. These diagnostics describe sensitivity without selecting normalization by outcome. Full expression matrices, REC50 projections, M–A data and interval estimates remain in Supplementary Table 4 and source data.'),
'Supplementary_Figure_6': (
'Complete regional effects and precision after source adjustment',
'a, All thirty members across eight specifications: eleven pairs or ten same-section pairs, TMM or library-only normalization, and baseline (B) or source-adjusted (A) models. Dots mark measured-member BH q < 0.05; slashes mark count ineligibility. The full range and fixed order are retained. b, Complete adjusted TMM estimates and approximate QL-Wald 95% intervals for both datasets, aligned with a. Identical axes contain every interval; NA denotes ineligible members. c, Directional and mixed-direction programme q values for baseline/adjusted TMM models, with separate four-programme BH families. Bold values are below 0.05; rounded display values do not replace full-precision results. d, Within-patient variance inflation factors for region and source proxies, with residual model degrees of freedom. Column groups identify the paired datasets and TMM/library normalization. Adjustment leaves seven residual degrees of freedom in eleven pairs and six in the same-section subset. The interval and diagnostic displays retain the loss of precision alongside coefficient changes. All eight specifications and complete intervals are in Supplementary Table 8.')}
